USE `universitymanagementsystem`;


DROP TABLE IF EXISTS DEPARTMENT;

CREATE TABLE DEPARTMENT(
    ID BIGINT NOT NULL auto_increment,
    VERSION INT,
    MODIFIED_AT TIMESTAMP,
    NAME VARCHAR(50) NOT NULL,
  primary key(`ID`)
);

DROP TABLE IF EXISTS PROGRAM;

CREATE TABLE PROGRAM(
    ID BIGINT NOT NULL auto_increment,
    VERSION INT,
    MODIFIED_AT TIMESTAMP,
    NAME VARCHAR(50),
    DEPARTMENT BIGINT NOT NULL,
    FOREIGN KEY (DEPARTMENT) REFERENCES DEPARTMENT(ID),
  primary key(`ID`)
);

DROP TABLE IF EXISTS PERSON;

CREATE TABLE PERSON(
    ID BIGINT NOT NULL auto_increment,
    USERNAME VARCHAR(50) UNIQUE NOT NULL,
    FIRST_NAME VARCHAR(50) NOT NULL,
    LAST_NAME VARCHAR(50) NOT NULL,
    VERSION INT,
    MODIFIED_AT TIMESTAMP,
    PASSWORD VARCHAR(100) NOT NULL,
    primary key (`id`)
);

DROP TABLE IF EXISTS ROLES;

CREATE TABLE ROLES(
    ID BIGINT NOT NULL auto_increment,
    NAME VARCHAR(20) NOT NULL,
  primary key(`ID`)
);

DROP TABLE IF EXISTS PERSON_ROLES;

CREATE TABLE `PERSON_ROLES` (
  `user_id` BIGINT NOT NULL,
  `role_id` BIGINT NOT NULL,
  
  PRIMARY KEY (`user_id`,`role_id`),
  
  KEY `FK_ROLE_idx` (`role_id`),
  
  CONSTRAINT `FK_USER_05` FOREIGN KEY (`user_id`) 
  REFERENCES `user` (`id`) 
  ON DELETE NO ACTION ON UPDATE NO ACTION,
  
  CONSTRAINT `FK_ROLE` FOREIGN KEY (`role_id`) 
  REFERENCES `role` (`id`) 
  ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS FACULTYMEMBER;

CREATE TABLE FACULTYMEMBER
(
  ID BIGINT NOT NULL auto_increment,
  VERSION INT,
  MODIFIED_AT TIMESTAMP,
  FIRST_NAME VARCHAR(50) NOT NULL,
  LAST_NAME VARCHAR(50) NOT NULL,
  STATUS VARCHAR(16),
  HIRING_DATE TIMESTAMP,
  DEPARTMENT BIGINT  NOT NULL,
  FOREIGN KEY (DEPARTMENT) REFERENCES DEPARTMENT(ID),
  primary key(`ID`)
);

DROP TABLE IF EXISTS STAFFMEMBER;

CREATE TABLE STAFFMEMBER
(
  ID BIGINT NOT NULL auto_increment,
  VERSION INT,
  MODIFIED_AT TIMESTAMP,
  FIRST_NAME VARCHAR(50) NOT NULL,
  LAST_NAME VARCHAR(50) NOT NULL,
  HIRING_DATE TIMESTAMP,
  DEPARTMENT BIGINT NOT NULL,
  STATUS VARCHAR(16),
  FOREIGN KEY (DEPARTMENT) REFERENCES DEPARTMENT(ID),
  primary key(`ID`)
);

DROP TABLE IF EXISTS STUDENT;

CREATE TABLE STUDENT
(
  ID BIGINT NOT NULL auto_increment,
  VERSION INT,
  MODIFIED_AT TIMESTAMP,
--   FIRST_NAME VARCHAR(50) NOT NULL,
--   LAST_NAME VARCHAR(50) NOT NULL,
  ENROLLMENT_DATE TIMESTAMP,
  MAJOR BIGINT,
  STATUS VARCHAR(18),
  FOREIGN KEY (MAJOR) REFERENCES PROGRAM(ID),
  primary key(`ID`)
);

DROP TABLE IF EXISTS COURSE;

CREATE TABLE COURSE(
  ID BIGINT NOT NULL auto_increment,
  VERSION INT,
  MODIFIED_AT TIMESTAMP,
  NAME VARCHAR(50) NOT NULL,
  INSTRUCTOR BIGINT NOT NULL,
  DEPARTMENT BIGINT NOT NULL,
  FOREIGN KEY (INSTRUCTOR) REFERENCES FACULTYMEMBER(ID),
  FOREIGN KEY (DEPARTMENT) REFERENCES DEPARTMENT(ID),
  primary key(`ID`)
);

DROP TABLE IF EXISTS COURSE_GRADE;

CREATE TABLE COURSE_GRADE(
    STUDENT_ID BIGINT NOT NULL,
    COURSE_ID BIGINT NOT NULL,
    MODIFIED_AT TIMESTAMP,
    GRADE VARCHAR(6),
    FOREIGN KEY (STUDENT_ID) REFERENCES STUDENT(ID),
    FOREIGN KEY (COURSE_ID) REFERENCES COURSE(ID),
    CONSTRAINT COURSE_GRADE_KEY PRIMARY KEY (STUDENT_ID, COURSE_ID)
);

