
INSERT INTO ROLES(ID, NAME) VALUES (1, 'ROLE_ADMIN');
INSERT INTO ROLES(ID, NAME) VALUES (2, 'ROLE_STUDENT');
INSERT INTO ROLES(ID, NAME) VALUES (3, 'ROLE_FACULTY_MEMBER');
INSERT INTO ROLES(ID, NAME) VALUES (4, 'ROLE_STAFF_MEMBER');
