INSERT INTO DEPARTMENT (ID, NAME, VERSION) VALUES (1, 'Mathematics', 1);
INSERT INTO FACULTYMEMBER(ID, FIRST_NAME, LAST_NAME, VERSION,STATUS, DEPARTMENT) VALUES (1, 'David', 'Folk', 1, 'FULL_TIME', 1);
INSERT INTO FACULTYMEMBER(ID, FIRST_NAME, LAST_NAME, VERSION,STATUS, DEPARTMENT) VALUES (2, 'Walter', 'White', 1, 'SABBATICAL', 1);

INSERT INTO PROGRAM (ID, NAME, VERSION, DEPARTMENT)VALUES (1, 'Topology', 1, 1);

INSERT INTO COURSE (ID, NAME, INSTRUCTOR, VERSION, DEPARTMENT) VALUES (1, 'Intro to Topology', 1, 1, 1);
INSERT INTO COURSE (ID, NAME, INSTRUCTOR, VERSION, DEPARTMENT) VALUES (2, 'Intro to Calculus', 1, 1, 1);
INSERT INTO COURSE (ID, NAME, INSTRUCTOR, VERSION, DEPARTMENT) VALUES (3, 'Intro to Math', 1, 1, 1);

INSERT INTO STAFFMEMBER (ID, FIRST_NAME, LAST_NAME, DEPARTMENT, VERSION) VALUES (1, 'Dyl', 'Pickle', 1, 1);
INSERT INTO STAFFMEMBER (ID, FIRST_NAME, LAST_NAME, DEPARTMENT, VERSION) VALUES (2, 'Delete', 'Me', 1, 1);

INSERT INTO STUDENT (ID, FIRST_NAME, LAST_NAME, VERSION, MAJOR, STATUS) VALUES (1, 'Dylan', 'Cechanowicz', 1, 1, 'GOOD_STANDING');
INSERT INTO STUDENT (ID, FIRST_NAME, LAST_NAME, VERSION, MAJOR, STATUS) VALUES (2, 'Tom', 'Brady', 1, 1, 'GOOD_STANDING');
INSERT INTO STUDENT (ID, FIRST_NAME, LAST_NAME, VERSION, MAJOR, STATUS) VALUES (3, 'Delete', 'Me', 1, 1, 'GOOD_STANDING');
