
-- Math Dep. Courses
INSERT INTO COURSE (ID, NAME, INSTRUCTOR, VERSION, DEPARTMENT) VALUES (1, 'Intro to Topology', 3, 1, 1);
INSERT INTO COURSE (ID, NAME, INSTRUCTOR, VERSION, DEPARTMENT) VALUES (2, 'Multi Variable Calculus', 1, 1, 1);
INSERT INTO COURSE (ID, NAME, INSTRUCTOR, VERSION, DEPARTMENT) VALUES (3, 'Intro to Math', 3, 1, 1);

-- Bio. Dep. Courses
INSERT INTO COURSE (ID, NAME, INSTRUCTOR, VERSION, DEPARTMENT) VALUES (4, 'Intro to Biology', 4, 1, 2);
INSERT INTO COURSE (ID, NAME, INSTRUCTOR, VERSION, DEPARTMENT) VALUES (5, 'Biochemistry', 6, 1, 2);
INSERT INTO COURSE (ID, NAME, INSTRUCTOR, VERSION, DEPARTMENT) VALUES (6, 'Intro to Plants', 5, 1, 2);

-- Comp. Sci. Dep. Courses
INSERT INTO COURSE (ID, NAME, INSTRUCTOR, VERSION, DEPARTMENT) VALUES (7, 'Intro to Java', 7, 1, 3);
INSERT INTO COURSE (ID, NAME, INSTRUCTOR, VERSION, DEPARTMENT) VALUES (8, 'Algorithms & Data Structures', 8, 1, 3);
INSERT INTO COURSE (ID, NAME, INSTRUCTOR, VERSION, DEPARTMENT) VALUES (9, 'Intro Androids API', 9, 1, 3);

-- Chemistry Dep. Courses
INSERT INTO COURSE (ID, NAME, INSTRUCTOR, VERSION, DEPARTMENT) VALUES (10, 'Intro Physical Chemistry', 11, 1, 4);
INSERT INTO COURSE (ID, NAME, INSTRUCTOR, VERSION, DEPARTMENT) VALUES (11, 'Organic Chemistry', 10, 1, 4);
INSERT INTO COURSE (ID, NAME, INSTRUCTOR, VERSION, DEPARTMENT) VALUES (12, 'Applied Chemistry', 10, 1, 4);