-- Mathematics Department
INSERT INTO STUDENT(ID, MAJOR, STATUS, VERSION) VALUES (14, 1, 'GRADUATED', 1);
INSERT INTO PERSON(ID, USERNAME, FIRST_NAME, LAST_NAME, VERSION, PASSWORD) VALUES (14, 'Dcechanowicz', 'Dylan', 'Cechanowicz',1, '$2a$10$GkhZyRLaflX.v9KvbIkmKuz9tZgc/t6EzcR8YedWOOeq8Fvqqnbv.');
INSERT INTO PERSON_ROLES(ID, ROLE) VALUES (14, 2);

INSERT INTO STUDENT(ID, MAJOR, STATUS, VERSION) VALUES (15, 1,'GOOD_STANDING', 1);
INSERT INTO PERSON(ID, USERNAME, FIRST_NAME, LAST_NAME, VERSION, PASSWORD) VALUES (15, 'Mokafor', 'Mairtin', 'Okafor', 1, '$2a$10$GkhZyRLaflX.v9KvbIkmKuz9tZgc/t6EzcR8YedWOOeq8Fvqqnbv.');
INSERT INTO PERSON_ROLES(ID, ROLE) VALUES (15, 2);

INSERT INTO STUDENT(ID, MAJOR, STATUS, VERSION) VALUES (16, 2,'GOOD_STANDING', 1);
INSERT INTO PERSON(ID, USERNAME, FIRST_NAME, LAST_NAME, VERSION, PASSWORD) VALUES (16, 'Iantal', 'Izabela', 'Antal', 1, '$2a$10$GkhZyRLaflX.v9KvbIkmKuz9tZgc/t6EzcR8YedWOOeq8Fvqqnbv.');
INSERT INTO PERSON_ROLES(ID, ROLE) VALUES (16, 2);

-- Biology Department
INSERT INTO STUDENT(ID, MAJOR, STATUS, VERSION) VALUES (17, 3, 'ACADEMIC_PROBATION', 1);
INSERT INTO PERSON(ID, USERNAME, FIRST_NAME, LAST_NAME, VERSION, PASSWORD) VALUES (17, 'Nagricola', 'Nirmala', 'Agricola', 1, '$2a$10$GkhZyRLaflX.v9KvbIkmKuz9tZgc/t6EzcR8YedWOOeq8Fvqqnbv.');
INSERT INTO PERSON_ROLES(ID, ROLE) VALUES (17, 2);

INSERT INTO STUDENT(ID, MAJOR, STATUS, VERSION) VALUES (18, 4, 'GOOD_STANDING', 1);
INSERT INTO PERSON(ID, USERNAME, FIRST_NAME, LAST_NAME, VERSION, PASSWORD) VALUES (18, 'Sholub', 'Scaevola', 'Holub', 1, '$2a$10$GkhZyRLaflX.v9KvbIkmKuz9tZgc/t6EzcR8YedWOOeq8Fvqqnbv.');
INSERT INTO PERSON_ROLES(ID, ROLE) VALUES (18, 2);

INSERT INTO STUDENT(ID, MAJOR, STATUS, VERSION) VALUES (19, 4, 'GOOD_STANDING', 1);
INSERT INTO PERSON(ID, USERNAME, FIRST_NAME, LAST_NAME, VERSION, PASSWORD) VALUES (19, 'Pkirby', 'Petya', 'Kirby', 1, '$2a$10$GkhZyRLaflX.v9KvbIkmKuz9tZgc/t6EzcR8YedWOOeq8Fvqqnbv.');
INSERT INTO PERSON_ROLES(ID, ROLE) VALUES (19, 2);

-- Comp. Sci. Department
INSERT INTO STUDENT(ID, MAJOR, STATUS, VERSION) VALUES (20, 5, 'ACADEMIC_PROBATION', 1);
INSERT INTO PERSON(ID, USERNAME, FIRST_NAME, LAST_NAME, VERSION, PASSWORD) VALUES (20, 'Byun', 'Beyza', 'Yun', 1, '$2a$10$GkhZyRLaflX.v9KvbIkmKuz9tZgc/t6EzcR8YedWOOeq8Fvqqnbv.');
INSERT INTO PERSON_ROLES(ID, ROLE) VALUES (20, 2);

INSERT INTO STUDENT(ID, MAJOR, STATUS, VERSION) VALUES (21, 6, 'ACADEMIC_PROBATION', 1);
INSERT INTO PERSON(ID, USERNAME, FIRST_NAME, LAST_NAME, VERSION, PASSWORD) VALUES (21, 'Mwaterman', 'Magda', 'Waterman',1, '$2a$10$GkhZyRLaflX.v9KvbIkmKuz9tZgc/t6EzcR8YedWOOeq8Fvqqnbv.');
INSERT INTO PERSON_ROLES(ID, ROLE) VALUES (21, 2);

INSERT INTO STUDENT(ID, MAJOR, STATUS, VERSION) VALUES (22, 5, 'GOOD_STANDING', 1);
INSERT INTO PERSON(ID, USERNAME, FIRST_NAME, LAST_NAME, VERSION, PASSWORD) VALUES (22, 'Kroutsalanainen', 'Kamala', 'Ruotsalanainen', 1, '$2a$10$GkhZyRLaflX.v9KvbIkmKuz9tZgc/t6EzcR8YedWOOeq8Fvqqnbv.');
INSERT INTO PERSON_ROLES(ID, ROLE) VALUES (22, 2);

-- Chemistry Department
INSERT INTO STUDENT(ID, MAJOR, STATUS, VERSION) VALUES (23, 8, 'GOOD_STANDING', 1);
INSERT INTO PERSON(ID, USERNAME, FIRST_NAME, LAST_NAME, VERSION, PASSWORD) VALUES (23, 'Ggabor', 'Gotthold', 'Gabor',1, '$2a$10$GkhZyRLaflX.v9KvbIkmKuz9tZgc/t6EzcR8YedWOOeq8Fvqqnbv.');
INSERT INTO PERSON_ROLES(ID, ROLE) VALUES (23, 2);

INSERT INTO STUDENT(ID, MAJOR, STATUS, VERSION) VALUES (24, 8, 'GOOD_STANDING', 1);
INSERT INTO PERSON(ID, USERNAME, FIRST_NAME, LAST_NAME, VERSION, PASSWORD) VALUES (24, 'Mravenna', 'Menodora', 'Ravenna', 1, '$2a$10$GkhZyRLaflX.v9KvbIkmKuz9tZgc/t6EzcR8YedWOOeq8Fvqqnbv.');
INSERT INTO PERSON_ROLES(ID, ROLE) VALUES (24, 2);

INSERT INTO STUDENT(ID, MAJOR, STATUS, VERSION) VALUES (25, 7, 'NOT_ENROLLED', 1);
INSERT INTO PERSON(ID, USERNAME, FIRST_NAME, LAST_NAME, VERSION, PASSWORD) VALUES (25, 'Nahmed', 'Nishant', 'Ahmed', 1, '$2a$10$GkhZyRLaflX.v9KvbIkmKuz9tZgc/t6EzcR8YedWOOeq8Fvqqnbv.');
INSERT INTO PERSON_ROLES(ID, ROLE) VALUES (25, 2);

INSERT INTO STUDENT(ID, MAJOR, STATUS, VERSION) VALUES (26, 7, 'GOOD_STANDING', 1);
INSERT INTO PERSON(ID, USERNAME, FIRST_NAME, LAST_NAME, VERSION, PASSWORD) VALUES (26, 'Jbartholomew', 'John', 'Bartholomew', 1, '$2a$10$8z0merUtpplCE0E5GFC0TeulzIzvXRhiayd5MM1IFbXeEJ5Pj4XnG');
INSERT INTO PERSON_ROLES(ID, ROLE) VALUES (26, 2);



