INSERT INTO DEPARTMENT (ID, NAME, VERSION) VALUES (1, 'Mathematics', 1);
INSERT INTO DEPARTMENT (ID, NAME, VERSION) VALUES (2, 'Biology', 1);
INSERT INTO DEPARTMENT (ID, NAME, VERSION) VALUES (3, 'Computer Science', 1);
INSERT INTO DEPARTMENT (ID, NAME, VERSION) VALUES (4, 'Chemistry', 1);
