-- Math Department
-- INSERT INTO FACULTYMEMBER(ID, FIRST_NAME, LAST_NAME, VERSION, STATUS, DEPARTMENT) VALUES (1, 'David', 'Folk', 1, 'FULL_TIME', 1);
INSERT INTO FACULTYMEMBER(ID, VERSION, STATUS, DEPARTMENT) VALUES (1, 1, 'FULL_TIME', 1);
INSERT INTO PERSON(ID, USERNAME, FIRST_NAME, LAST_NAME, VERSION, PASSWORD) VALUES (1, 'Dfolk', 'David', 'Folk', 1, '$2a$10$GkhZyRLaflX.v9KvbIkmKuz9tZgc/t6EzcR8YedWOOeq8Fvqqnbv.');
INSERT INTO PERSON_ROLES(ID, ROLE) VALUES (1, 3);

-- INSERT INTO FACULTYMEMBER(ID, FIRST_NAME, LAST_NAME, VERSION, STATUS, DEPARTMENT) VALUES (2, 'Gary', 'Kasparov', 1, 'SABBATICAL', 1);
INSERT INTO FACULTYMEMBER(ID, VERSION, STATUS, DEPARTMENT) VALUES (2, 1, 'SABBATICAL', 1);
INSERT INTO PERSON(ID, USERNAME, FIRST_NAME, LAST_NAME, VERSION, PASSWORD) VALUES (2, 'GKasparov', 'Gary', 'Kasparov', 1, '$2a$10$GkhZyRLaflX.v9KvbIkmKuz9tZgc/t6EzcR8YedWOOeq8Fvqqnbv.');
INSERT INTO PERSON_ROLES(ID, ROLE) VALUES (2, 3);

-- INSERT INTO FACULTYMEMBER(ID, FIRST_NAME, LAST_NAME, VERSION, STATUS, DEPARTMENT) VALUES (3, 'Christopher', 'Gardner', 1, 'TENURED', 1);
INSERT INTO FACULTYMEMBER(ID, VERSION, STATUS, DEPARTMENT) VALUES (3, 1, 'TENURED', 1);
INSERT INTO PERSON(ID, USERNAME, FIRST_NAME, LAST_NAME, VERSION, PASSWORD) VALUES (3, 'Cgardner', 'Christoper', 'Gardner', 1, '$2a$10$GkhZyRLaflX.v9KvbIkmKuz9tZgc/t6EzcR8YedWOOeq8Fvqqnbv.');
INSERT INTO PERSON_ROLES(ID, ROLE) VALUES (3, 3);

-- Biology Department
-- INSERT INTO FACULTYMEMBER(ID, FIRST_NAME, LAST_NAME, VERSION, STATUS, DEPARTMENT) VALUES (4, 'Lisa', 'Stackhouse', 1, 'FULL_TIME', 2);
INSERT INTO FACULTYMEMBER(ID, VERSION, STATUS, DEPARTMENT) VALUES (4, 1, 'FULL_TIME', 2);
INSERT INTO PERSON(ID, USERNAME, FIRST_NAME, LAST_NAME, VERSION, PASSWORD) VALUES (4, 'Lstackhouse', 'Lisa', 'Stackhouse', 1, '$2a$10$GkhZyRLaflX.v9KvbIkmKuz9tZgc/t6EzcR8YedWOOeq8Fvqqnbv.');
INSERT INTO PERSON_ROLES(ID, ROLE) VALUES (4, 3);

-- INSERT INTO FACULTYMEMBER(ID, FIRST_NAME, LAST_NAME, VERSION, STATUS, DEPARTMENT) VALUES (5, 'Greg', 'Wilmes', 1, 'PART_TIME', 2);
INSERT INTO FACULTYMEMBER(ID, VERSION, STATUS, DEPARTMENT) VALUES (5, 1, 'PART_TIME', 2);
INSERT INTO PERSON(ID, USERNAME, FIRST_NAME, LAST_NAME, VERSION, PASSWORD) VALUES (5, 'Gwilmes', 'Greg', 'Wilmes', 1, '$2a$10$GkhZyRLaflX.v9KvbIkmKuz9tZgc/t6EzcR8YedWOOeq8Fvqqnbv.');
INSERT INTO PERSON_ROLES(ID, ROLE) VALUES (5, 3);

-- INSERT INTO FACULTYMEMBER(ID, FIRST_NAME, LAST_NAME, VERSION, STATUS, DEPARTMENT) VALUES (6, 'Timothy', 'Brewer', 1, 'RETIRED', 2);
INSERT INTO FACULTYMEMBER(ID, VERSION, STATUS, DEPARTMENT) VALUES (6, 1, 'RETIRED', 2);
INSERT INTO PERSON(ID, USERNAME, FIRST_NAME, LAST_NAME, VERSION, PASSWORD) VALUES (6, 'Tbrewer', 'Timothy', 'Brewer', 1, '$2a$10$GkhZyRLaflX.v9KvbIkmKuz9tZgc/t6EzcR8YedWOOeq8Fvqqnbv.');
INSERT INTO PERSON_ROLES(ID, ROLE) VALUES (6, 3);

-- Comp. Sci. Department
-- INSERT INTO FACULTYMEMBER(ID, FIRST_NAME, LAST_NAME, VERSION, STATUS, DEPARTMENT) VALUES (7, 'Khaled', 'Mansour', 1, 'SABBATICAL', 3);
INSERT INTO FACULTYMEMBER(ID, VERSION, STATUS, DEPARTMENT) VALUES (7, 1, 'SABBATICAL', 3);
INSERT INTO PERSON(ID, USERNAME, FIRST_NAME, LAST_NAME, VERSION, PASSWORD) VALUES (7, 'Kmansour', 'Khaled', 'Mansour', 1, '$2a$10$GkhZyRLaflX.v9KvbIkmKuz9tZgc/t6EzcR8YedWOOeq8Fvqqnbv.');
INSERT INTO PERSON_ROLES(ID, ROLE) VALUES (7, 3);

-- INSERT INTO FACULTYMEMBER(ID, FIRST_NAME, LAST_NAME, VERSION, STATUS, DEPARTMENT) VALUES (8, 'Jonathan', 'Haley', 1, 'FULL_TIME', 3);
INSERT INTO FACULTYMEMBER(ID, VERSION, STATUS, DEPARTMENT) VALUES (8, 1, 'FULL_TIME', 3);
INSERT INTO PERSON(ID, USERNAME, FIRST_NAME, LAST_NAME, VERSION, PASSWORD) VALUES (8, 'Jhaley', 'Jonathan', 'Haley', 1, '$2a$10$GkhZyRLaflX.v9KvbIkmKuz9tZgc/t6EzcR8YedWOOeq8Fvqqnbv.');
INSERT INTO PERSON_ROLES(ID, ROLE) VALUES (8, 3);

-- INSERT INTO FACULTYMEMBER(ID, FIRST_NAME, LAST_NAME, VERSION, STATUS, DEPARTMENT) VALUES (9, 'Micheal', 'Ashley', 1, 'SABBATICAL', 3);
INSERT INTO FACULTYMEMBER(ID, VERSION, STATUS, DEPARTMENT) VALUES (9, 1, 'SABBATICAL', 3);
INSERT INTO PERSON(ID, USERNAME, FIRST_NAME, LAST_NAME, VERSION, PASSWORD) VALUES (9, 'Mashley', 'Micheal', 'Ashley', 1, '$2a$10$GkhZyRLaflX.v9KvbIkmKuz9tZgc/t6EzcR8YedWOOeq8Fvqqnbv.');
INSERT INTO PERSON_ROLES(ID, ROLE) VALUES (9, 3);

-- Chemistry Department
-- INSERT INTO FACULTYMEMBER(ID, FIRST_NAME, LAST_NAME, VERSION, STATUS, DEPARTMENT) VALUES (10, 'Walter', 'White', 1, 'TENURED', 4);
INSERT INTO FACULTYMEMBER(ID, VERSION, STATUS, DEPARTMENT) VALUES (10, 1, 'TENURED', 4);
INSERT INTO PERSON(ID, USERNAME, FIRST_NAME, LAST_NAME, VERSION, PASSWORD) VALUES (10, 'hiesenburg', 'Walter', 'White', 1, '$2a$10$GkhZyRLaflX.v9KvbIkmKuz9tZgc/t6EzcR8YedWOOeq8Fvqqnbv.');
INSERT INTO PERSON_ROLES(ID, ROLE) VALUES (10, 3);

-- INSERT INTO FACULTYMEMBER(ID, FIRST_NAME, LAST_NAME, VERSION, STATUS, DEPARTMENT) VALUES (11, 'Walter', 'White Jr.', 1, 'PART_TIME', 4);
INSERT INTO FACULTYMEMBER(ID,  VERSION, STATUS, DEPARTMENT) VALUES (11, 1, 'PART_TIME', 4);
INSERT INTO PERSON(ID, USERNAME, FIRST_NAME, LAST_NAME, VERSION, PASSWORD) VALUES (11, 'Wwhite', 'Walter', 'White Jr.', 1, '$2a$10$GkhZyRLaflX.v9KvbIkmKuz9tZgc/t6EzcR8YedWOOeq8Fvqqnbv.');
INSERT INTO PERSON_ROLES(ID, ROLE) VALUES (11, 3);

-- INSERT INTO FACULTYMEMBER(ID, FIRST_NAME, LAST_NAME, VERSION, STATUS, DEPARTMENT) VALUES (12, 'Walter', 'Ross', 1, 'RETIRED', 4);
INSERT INTO FACULTYMEMBER(ID, VERSION, STATUS, DEPARTMENT) VALUES (12, 1, 'RETIRED', 4);
INSERT INTO PERSON(ID, USERNAME, FIRST_NAME, LAST_NAME, VERSION, PASSWORD) VALUES (12, 'Wross', 'Walter', 'Ross', 1, '$2a$10$GkhZyRLaflX.v9KvbIkmKuz9tZgc/t6EzcR8YedWOOeq8Fvqqnbv.');
INSERT INTO PERSON_ROLES(ID, ROLE) VALUES (12, 3);
